### ISSUE TITLE
Micro Smart Plug lost Power transmition

### ISSUE THREAD

**Issue by philT06** [caseda/com.nodon#14]
After 2 days transmition ok, the Power always display O W (the real is 970 W, The energie increase ok. Memory  for NODON seems to be great (16.4 MB for 1 Micro Smart Plug and 1 Octan remote). After 1 Factory Reset (exclusion before and after inclusion) the power is good for 2 days and after lost again. In between I reboot my homey, and loose 1 time the general power but for 10 minutes.

**Comment by caseda** [comment]
This is not an error of the app and more likely a range issue or your device is broken, what is the distance?

the minimal app memory size is 14MB, even without any devices included, so 16.4 is completely normal.

**Comment by philT06** [comment]
10 m inside (1 wall inside) 2 m outside and one other wall + 1m

**Comment by caseda** [comment]
10M is really on the edge of the abilities of Homey, especially with a wall in between, so put it closer and see if it keeps working.

**Comment by philT06** [comment]
Thank's i'll try

**Comment by philT06** [comment]
Effectivement après un nouveau Factory resset la mise en place d'un repeater (Aeotec) le suivi de puissance fonctionne depuis donc environ 24 jours. La puissance mémoire reste à 9MO (elle atteignait 24 lors du dernier bug).

**Comment by caseda** [comment]
My French is non existend so please keep it English, but good to know that a repeater fixed it.

an issue isn't an issue of the app, if it is fixed by other means then the app itself, so the lower value of the memory when the distance is too big is not an app issue as the range isn't defined by the app, neither is the how Homey handels (too) bigger distances, as that is taken care of by Homey's core that I can't touch.
