### ISSUE TITLE
ZWAVE SMART PLUG

### ISSUE THREAD

**Issue by ericms35** [caseda/com.nodon#26]
Hi. I have an issu e with Wave Smart plug , and HOMEY PRO 2019
These  devices (10,31 and 59) with an extremely high Rx value ;One sends 1.9 million messages and another sends 1.2 million messages to Homey Pro, this is much to high. 
The devices are constantly triggering on the "power meter value", it looks like the "previous power meter value" is not stored correctly (previous value is always 0,0,0,0)
I don'y see any parameter to set up in Advanced settings.
Is it a know issue?
Thank you for kind help 
Regards

**Comment by caseda** [comment]
Is this the micro smart plug?
If yes, then this is a known issue on some micro smart plug where the parameter is ignored, this can't be fixed/changed by Homey as it is a _device firmware_ issue, sometimes it helps to remove it, and re-include it, but doesn't always work, and might come back after some time.
I've already tried to make nodon to fix the issue, but they never came with a newer firmware version, and they have, since a few years, stopped supporting all their Z-Wave devices unfortunately.
